### ISSUE TITLE
Fehler Building SvelteKit App / make build-frontend

### ISSUE THREAD

**Issue by RealNetcrusher** [dascr/dascr-board#18]
Hallo,

beim Versuch das Frontend auf einem Raspberry 4 mit Raspberry Pi OS x64 ans Laufen zu bekommen, bleibt der make-Aufruf bei svelte-kit build hängen. Das Backend lässt sich problemlos erstellen.

```
pi@raspberrypi:/opt/dascr/dascr-board $ make build-frontend
[*] Cleanup SvelteKit App
[OK] Cleanup done
[*] Building SvelteKit App

> dose@1.0.0 tailwind:build /opt/dascr/dascr-board/frontend
> cross-env TAILWIND_MODE=build cross-env NODE_ENV=production postcss src/styles/tailwind.css -o src/styles/tailwind-output.css




warn - You have enabled the JIT engine which is currently in preview.
warn - Preview features are not covered by semver, may introduce breaking changes, and can change at any time.
Source path: /opt/dascr/dascr-board/frontend/src/styles/tailwind.css
Setting up new context...
Finding changed files: 16.611ms
Generate rules: 161.866ms
Build stylesheet: 3.52ms
Potential classes:  2611
Active contexts:  1
Content match entries 1206
JIT TOTAL: 570.005ms



> dose@1.0.0 build:only /opt/dascr/dascr-board/frontend
> svelte-kit build

> config.kit.router has been moved to config.kit.browser.router
    at file:///opt/dascr/dascr-board/frontend/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.260_svelte@3.46.4/node_modules/@sveltejs/kit/dist/cli.js:874:10
    at file:///opt/dascr/dascr-board/frontend/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.260_svelte@3.46.4/node_modules/@sveltejs/kit/dist/cli.js:766:43
    at file:///opt/dascr/dascr-board/frontend/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.260_svelte@3.46.4/node_modules/@sveltejs/kit/dist/cli.js:752:18
    at file:///opt/dascr/dascr-board/frontend/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.260_svelte@3.46.4/node_modules/@sveltejs/kit/dist/cli.js:752:18
    at validate_config (file:///opt/dascr/dascr-board/frontend/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.260_svelte@3.46.4/node_modules/@sveltejs/kit/dist/cli.js:936:9)
    at load_config (file:///opt/dascr/dascr-board/frontend/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.260_svelte@3.46.4/node_modules/@sveltejs/kit/dist/cli.js:913:20)
    at async file:///opt/dascr/dascr-board/frontend/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.260_svelte@3.46.4/node_modules/@sveltejs/kit/dist/cli.js:1048:19
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dose@1.0.0 build:only: `svelte-kit build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dose@1.0.0 build:only script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2022-02-07T20_44_13_888Z-debug.log

```

/home/pi/.npm/_logs/2022-02-07T20_44_13_888Z-debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build:only' ]
2 info using npm@6.14.16
3 info using node@v14.19.0
4 verbose run-script [ 'prebuild:only', 'build:only', 'postbuild:only' ]
5 info lifecycle dose@1.0.0~prebuild:only: dose@1.0.0
6 info lifecycle dose@1.0.0~build:only: dose@1.0.0
7 verbose lifecycle dose@1.0.0~build:only: unsafe-perm in lifecycle true
8 verbose lifecycle dose@1.0.0~build:only: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/opt/dascr/dascr-board/frontend/node_modules/.bin:/opt/dascr/dascr-board/frontend/node_modules/.bin:/usr/pnpm-global/5/node_modules/.pnpm/pnpm@6.30.0/node_m>
9 verbose lifecycle dose@1.0.0~build:only: CWD: /opt/dascr/dascr-board/frontend
10 silly lifecycle dose@1.0.0~build:only: Args: [ '-c', 'svelte-kit build' ]
11 silly lifecycle dose@1.0.0~build:only: Returned: code: 1  signal: null
12 info lifecycle dose@1.0.0~build:only: Failed to exec build:only script
13 verbose stack Error: dose@1.0.0 build:only: `svelte-kit build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1058:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
14 verbose pkgid dose@1.0.0
15 verbose cwd /opt/dascr/dascr-board/frontend
16 verbose Linux 5.10.92-v8+
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build:only"
18 verbose node v14.19.0
19 verbose npm  v6.14.16
20 error code ELIFECYCLE
21 error errno 1
22 error dose@1.0.0 build:only: `svelte-kit build`
22 error Exit status 1
23 error Failed at the dose@1.0.0 build:only script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
Leider habe ich bei Google auch keine treffende Antwort auf die Meldung "config.kit.router has been moved to config.kit.browser.router" gefunden.

```
yarn --version
1.22.17

node --version
v14.19.0

pnpm
Version 6.30.0

npm --version
6.14.16

gcc version 10.2.1 20210110 (Debian 10.2.1-6)

go version
go version go1.17.6 linux/arm64

git --version
git version 2.30.2

Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

```

Hier komme ich leider nicht weiter.

Danke für Unterstützung.

Viele Grüße

**Comment by patrickhener** [comment]
Commit #e0903b9a097f3248c727f93d2b1c63de428f2fc5 sollte das fixen. Es gab breaking changes in sveltekit und der Art wie man den Router konfiguriert. Check mal die neue Version aus und teste nochmals, danke.

**Comment by RealNetcrusher** [comment]
Perfekt, vielen Dank! Jetzt lässt sich das Frontend erstellen.
