### ISSUE TITLE
make build-frontend fails

### ISSUE THREAD

**Issue by ptahbe** [dascr/dascr-board#19]
Output of make build-frontend :

```
[*] Cleanup SvelteKit App
[OK] Cleanup done
[*] Building SvelteKit App

> dose@1.0.0 tailwind:build
> cross-env TAILWIND_MODE=build cross-env NODE_ENV=production postcss src/styles/tailwind.css -o src/styles/tailwind-output.css




warn - You have enabled the JIT engine which is currently in preview.
warn - Preview features are not covered by semver, may introduce breaking changes, and can change at any time.
Source path: /data/dascr-board/frontend/src/styles/tailwind.css
Setting up new context...
Finding changed files: 5.329ms
Generate rules: 52.277ms
Build stylesheet: 1.104ms
Potential classes:  2611
Active contexts:  1
Content match entries 1206
JIT TOTAL: 187.436ms



> dose@1.0.0 build:only
> svelte-kit build

file:///data/dascr-board/frontend/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.263_svelte@3.46.4/node_modules/@sveltejs/kit/dist/cli.js:1176
					} else if (allow?.length && cwd) {
					                 ^

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
npm ERR! code 1
npm ERR! path /data/dascr-board/frontend
npm ERR! command failed
npm ERR! command sh -c svelte-kit build

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/davy/.npm/_logs/2022-02-10T10_16_34_810Z-debug.log
make: *** [Makefile:52: build-frontend] Error 1
```

Log file :

```
0 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build:only' ]
1 info using npm@7.5.2
2 info using node@v12.22.5
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:/usr/share/nodejs/npm/npmrc Completed in 2ms
5 timing config:load:builtin Completed in 2ms
6 timing config:load:cli Completed in 2ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/data/dascr-board/frontend/.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/home/davy/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/etc/npmrc Completed in 1ms
13 timing config:load:global Completed in 1ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 2ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 10ms
19 verbose npm-session 20088485fea873b5
20 timing npm:load Completed in 19ms
21 timing command:run-script Completed in 112ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (/usr/share/nodejs/@npmcli/promise-spawn/index.js:64:27)
22 verbose stack     at ChildProcess.emit (events.js:314:20)
22 verbose stack     at maybeClose (internal/child_process.js:1022:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
23 verbose pkgid dose@1.0.0
24 verbose cwd /data/dascr-board/frontend
25 verbose Linux 5.13.0-28-generic
26 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build:only"
27 verbose node v12.22.5
28 verbose npm  v7.5.2
29 error code 1
30 error path /data/dascr-board/frontend
31 error command failed
32 error command sh -c svelte-kit build
33 verbose exit 1
```

These are the versions that are installed :
git : 2.32.0
go : 1.17.6
gcc : 11.2.0
node : 12.22.5
pnmp : 6.30.1
yarn : 1.22.17

I have no idea on how to solve this.

Can anyone help?

**Comment by patrickhener** [comment]
> pnpm version
{
  npm: '7.24.1',
  node: '14.17.5',
  v8: '8.4.371.23-node.76',
  uv: '1.41.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.2',
  modules: '83',
  nghttp2: '1.42.0',
  napi: '8',
  llhttp: '2.1.3',
  openssl: '1.1.1k',
  cldr: '39.0',
  icu: '69.1',
  tz: '2021a',
  unicode: '13.0'
}
```
Mine seams to be 14.17.5 as I tested building yesterday. Maybe you try updating and retry building?
Other than that the error is unfortunately not really specific.

In retrospective choosing svelte for frontend might have been a failure as they introduce breaking changes all the time.

**Comment by ptahbe** [comment]
Thx. Updating node to 14.19.0 did the trick.
